name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to Railway
        run: railway up --service tel-bot
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
